import type { RawImage } from './post/raw.js'

// Authored 16×16 emote glyphs — deterministic pixel arrays, no generation involved.
// Rendered by the engine as an overlay above a character's head.
export const EMOTE_KINDS = [
  'exclaim',
  'question',
  'heart',
  'star',
  'sleep',
  'hunger',
  'cold',
  'rain',
  'hurt',
  'talk',
  'idea',
  'anger',
] as const
export type EmoteKind = (typeof EMOTE_KINDS)[number]
export const EMOTE_SIZE = 16

// Warm-pastel palette, drawn from the Style Bible ramps.
export const EMOTE_PALETTE: Record<string, [number, number, number]> = {
  outline: [0x43, 0x39, 0x4a], // shadow dark
  cream: [0xff, 0xf6, 0xe9],
  rose: [0xe8, 0x78, 0x5a], // warm accent
  gold: [0xf4, 0xe2, 0x89],
  sky: [0xa8, 0xcf, 0xe0],
  deep: [0x5a, 0x8c, 0xab],
  wood: [0xe0, 0xa9, 0x5e],
  grey: [0xcf, 0xc6, 0xbc],
  purple: [0x8a, 0x6f, 0xa8],
  sage: [0x93, 0xb5, 0x73],
}

const CHAR_COLORS: Record<string, [number, number, number]> = {
  o: EMOTE_PALETTE.outline!,
  c: EMOTE_PALETTE.cream!,
  r: EMOTE_PALETTE.rose!,
  g: EMOTE_PALETTE.gold!,
  k: EMOTE_PALETTE.sky!,
  d: EMOTE_PALETTE.deep!,
  w: EMOTE_PALETTE.wood!,
  e: EMOTE_PALETTE.grey!,
  p: EMOTE_PALETTE.purple!,
  s: EMOTE_PALETTE.sage!,
}

const GLYPHS: Record<EmoteKind, string[]> = {
  exclaim: [
    '................',
    '......oooo......',
    '.....orrrro.....',
    '.....orrrro.....',
    '.....orrrro.....',
    '.....orrrro.....',
    '......orro......',
    '......orro......',
    '......orro......',
    '......oooo......',
    '................',
    '......oooo......',
    '.....orrrro.....',
    '.....orrrro.....',
    '......oooo......',
    '................',
  ],
  question: [
    '................',
    '....oooooo......',
    '...oggggggo.....',
    '...ogo..oggo....',
    '....oo...oggo...',
    '.........oggo...',
    '........oggo....',
    '.......oggo.....',
    '.......ogo......',
    '.......oo.......',
    '................',
    '.......oo.......',
    '......oggo......',
    '......oggo......',
    '.......oo.......',
    '................',
  ],
  heart: [
    '................',
    '................',
    '..ooo....ooo....',
    '.orrro..orrro...',
    'orrrrroorrrrro..',
    'orcrrrrrrrrrro..',
    'orrrrrrrrrrrro..',
    '.orrrrrrrrrro...',
    '..orrrrrrrro....',
    '...orrrrrro.....',
    '....orrrro......',
    '.....orro.......',
    '......oo........',
    '................',
    '................',
    '................',
  ],
  star: [
    '................',
    '.......oo.......',
    '......oggo......',
    '......oggo......',
    '.oooooogggoooooo',
    '.ogggggggggggggo',
    '..ogggggggggggo.',
    '...ogggggggggo..',
    '....ogggggggo...',
    '....ogggggggo...',
    '...oggg.oo.gggo.',
    '..ogg.......ggo.',
    '..oo.........oo.',
    '................',
    '................',
    '................',
  ],
  sleep: [
    '................',
    '........kkkkkk..',
    '............kk..',
    '...........kk...',
    '..........kk....',
    '.........kk.....',
    '........kkkkkk..',
    '....ddddd.......',
    '.......dd.......',
    '......dd........',
    '....ddddd.......',
    '.kkkk...........',
    '...kk...........',
    '..kk............',
    '.kkkk...........',
    '................',
  ],
  hunger: [
    '................',
    '................',
    '................',
    '................',
    '...ooooooooo....',
    '..owwwwwwwwwo...',
    '.owcwwcwwcwwwo..',
    '.owwwwwwwwwwwo..',
    '.owwwwwwwwwwwo..',
    '.owwwwwwwwwwwo..',
    '..owwwwwwwwwo...',
    '...ooooooooo....',
    '................',
    '................',
    '................',
    '................',
  ],
  cold: [
    '................',
    '................',
    '.......k........',
    '...k...k...k....',
    '....k..k..k.....',
    '.....k.k.k......',
    '......kkk.......',
    '..kkkkkkkkkkk...',
    '......kkk.......',
    '.....k.k.k......',
    '....k..k..k.....',
    '...k...k...k....',
    '.......k........',
    '................',
    '................',
    '................',
  ],
  rain: [
    '................',
    '................',
    '.......dd.......',
    '.......dd.......',
    '......dddd......',
    '......dddd......',
    '.....dddddd.....',
    '....dddddddd....',
    '....ddkddddd....',
    '....ddkddddd....',
    '....dddddddd....',
    '.....dddddd.....',
    '......dddd......',
    '................',
    '................',
    '................',
  ],
  hurt: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '..oooooooooooo..',
    '.owwcccccccwwo..',
    '.owwcceccecwwo..',
    '.owwccecceccwwo.',
    '.owwcccccccwwo..',
    '..oooooooooooo..',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  talk: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..oo...oo...oo..',
    '.occo.occo.occo.',
    '.occo.occo.occo.',
    '..oo...oo...oo..',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  idea: [
    '..g....gg....g..',
    '......oooo......',
    '.....oggggo.....',
    '....oggggggo....',
    '....ogcggggo....',
    '....ogcggggo....',
    '....oggggggo....',
    '.....oggggo.....',
    '......oggo......',
    '......oeeo......',
    '......oeeo......',
    '......oooo......',
    '................',
    '................',
    '................',
    '................',
  ],
  anger: [
    '................',
    '................',
    '................',
    '..rr.......rr...',
    '...rr.....rr....',
    '....r.....r.....',
    '................',
    '................',
    '....r.....r.....',
    '...rr.....rr....',
    '..rr.......rr...',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
}

export function renderEmote(kind: EmoteKind): RawImage {
  const rows = GLYPHS[kind]
  if (!rows) throw new Error(`unknown emote kind: ${kind}`)
  if (rows.length !== EMOTE_SIZE)
    throw new Error(`${kind}: expected ${EMOTE_SIZE} rows, got ${rows.length}`)
  const data = new Uint8ClampedArray(EMOTE_SIZE * EMOTE_SIZE * 4)
  rows.forEach((row, y) => {
    if (row.length !== EMOTE_SIZE)
      throw new Error(`${kind}: row ${y} has ${row.length} chars, expected ${EMOTE_SIZE}`)
    for (let x = 0; x < EMOTE_SIZE; x++) {
      const ch = row[x]!
      if (ch === '.') continue
      const color = CHAR_COLORS[ch]
      if (!color) throw new Error(`${kind}: unknown glyph char '${ch}' at ${x},${y}`)
      data.set([...color, 255], (y * EMOTE_SIZE + x) * 4)
    }
  })
  return { width: EMOTE_SIZE, height: EMOTE_SIZE, data }
}
