import { appendFileSync, cpSync, mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterAll, describe, expect, it } from 'vitest'
import {
  AssetCodex, BUILDINGS_CONTENT_DIR, INTERIOR_PIECES, LIBRARY, interiorCodexKind,
  listCommittedBuildings, listCommittedCast,
  listCommittedItems, openForgeDb, castArtCoverage, itemArtCoverage, coverageFailure,
  registerCommittedBuildings, structureArtCoverage, worldStructureKinds,
} from '@sj/forge'
import {
  DEFAULT_CONFIG, DWELLING_FOOTPRINTS, FOUNDER_IDS, ROAD_AUTOTILE_KEYS, TERRAIN_TILE_KINDS,
  makeCityTemplate, parseBuildingManifest, parseCharacterAtlasManifest, roadAutotileKind,
} from '@sj/shared'
import { INTERIOR_KINDS, cityStructures, parseLibraryItemManifest, resolveFurnishingKind } from '@sj/shared'
import {
  ingestCastArt, ingestLibraryArt, ingestProductionArt, ingestTerrainArt,
} from './ingestArt.js'
import { townStructuresFor } from './founders.js'

const dir = mkdtempSync(join(tmpdir(), 'sj-ingest-'))
afterAll(() => rmSync(dir, { recursive: true, force: true }))

describe('ingestProductionArt', () => {
  it('registers every committed cell and every committed sheet, idempotently', async () => {
    const db = openForgeDb(join(dir, 'codex.db'))
    const codex = new AssetCodex(db)

    const committed = listCommittedBuildings().length + listCommittedCast().length
    const first = await ingestProductionArt(db)
    expect(first).toHaveLength(committed)
    expect(first.every((e) => e.action === 'registered')).toBe(true)
    expect(first.map((e) => e.kind)).toContain('character:omar')
    expect(first.map((e) => e.kind)).toContain('standing_stone')
    // ★ `house`, not `hut`. This line asserted `hut` for a whole merge train after the template
    // renamed the kind, which is how a test can codify the very seam it was meant to hold.
    expect(first.map((e) => e.kind)).toContain('house')

    // the character record carries a parseable v4 atlas manifest with all 24 cells
    const omar = codex.listSince(0).find((r) => r.kind === 'character:omar')!
    expect(omar.class).toBe('rig-part')
    const atlas = parseCharacterAtlasManifest(omar.meta)!
    expect(Object.keys(atlas.cells)).toHaveLength(24)
    expect(atlas.figureH).toBeGreaterThan(0)

    // building record carries the v4-hires-building manifest as-is — and the shed's cell is a
    // COMMITTED one now, not the scratchpad fixture the old version of this test wrote
    const shed = codex.listSince(0).find((r) => r.kind === 'shed')!
    const shedManifest = parseBuildingManifest(shed.meta)!
    expect(shedManifest.footprint).toEqual({ w: 1, h: 1 })
    expect(shedManifest.cell.feetY).toBeLessThan(shedManifest.cell.h)

    // the founders' home: an authored, committed cell, at the footprint the template gives it
    const home = codex.listSince(0).find((r) => r.kind === 'house')!
    const homeManifest = parseBuildingManifest(home.meta)!
    expect(homeManifest.footprint).toEqual(DWELLING_FOOTPRINTS.house)
    expect(homeManifest.cell.feetY).toBeLessThan(homeManifest.cell.h)
    expect(codex.listSince(0).some((r) => r.kind === 'hut'), 'nothing places `hut`').toBe(false)
    // and its turned twin, which nothing places yet and everything is ready for
    expect(codex.listSince(0).some((r) => r.kind === 'house:se')).toBe(true)

    // second run: nothing new
    const second = await ingestProductionArt(db)
    expect(second.every((e) => e.action === 'unchanged')).toBe(true)
    expect(codex.listSince(0)).toHaveLength(first.length)

    db.close()
  }, 30_000)

  // Asked of a COPY of the committed root, so the claim is about the code and not the fixture.
  it('regenerated bytes register a NEW record that wins by seq', () => {
    const root = mkdtempSync(join(dir, 'regen-'))
    const one = listCommittedBuildings()[0]!
    cpSync(join(BUILDINGS_CONTENT_DIR, one.dir), join(root, one.dir), { recursive: true })
    const db = openForgeDb(join(dir, 'regen.db'))
    const codex = new AssetCodex(db)

    expect(registerCommittedBuildings(codex, { root }).map((e) => e.action)).toEqual(['registered'])
    expect(registerCommittedBuildings(codex, { root }).map((e) => e.action)).toEqual(['unchanged'])

    appendFileSync(join(root, one.dir, 'cell.png'), Buffer.from([0]))
    expect(registerCommittedBuildings(codex, { root }).map((e) => e.action)).toEqual(['registered'])
    const rows = codex.listSince(0).filter((r) => r.kind === one.codexKind)
    expect(rows).toHaveLength(2)
    expect(rows.at(-1)!.seq).toBeGreaterThan(rows[0]!.seq)
    db.close()
  }, 30_000)

  it('names half a cell instead of quietly drawing a prism', () => {
    const root = mkdtempSync(join(dir, 'half-'))
    const one = listCommittedBuildings()[0]!
    cpSync(join(BUILDINGS_CONTENT_DIR, one.dir), join(root, one.dir), { recursive: true })
    rmSync(join(root, one.dir, 'cell.png'))
    expect(() => listCommittedBuildings(root)).toThrow(new RegExp(`${one.dir}.*cell\\.png`))
  })

  // `structureArt.ts` cannot see `TOWN_STRUCTURES` in `founders.ts` — `@sj/forge` must not import
  // `@sj/gateway` — so the same coverage law is asked here, next to the source that can see it.
  describe('the dev town half of the coverage law', () => {
    const TEMPLATE = makeCityTemplate()

    it.each(['scripted', 'showcase'] as const)(
      'every kind the %s dev town stands resolves to committed art', (map) => {
        const town = townStructuresFor(map)
        expect(town.length).toBeGreaterThan(0)
        const { missing } = structureArtCoverage({
          structures: town,
          registered: listCommittedBuildings().map((c) => c.codexKind),
          creatable: worldStructureKinds({
            structures: [...TEMPLATE.structures, ...town],
            recipes: DEFAULT_CONFIG.structures.recipes,
          }),
        })
        expect(missing, `the ${map} town stands these and no codex cell answers:\n  ${missing.join('\n  ')}`)
          .toEqual([])
      })

    it('★ and it NAMES a kind the town stands with no art — the mutation', () => {
      // A DELTA, so it proves the same thing whether the tree is whole or already broken:
      // standing one more kind in the fixture town adds exactly one failure and no other.
      const registered = listCommittedBuildings().map((c) => c.codexKind)
      const coverage = (town: readonly { kind: string }[]): string[] => structureArtCoverage({
        structures: town,
        registered,
        creatable: worldStructureKinds({
          structures: [...TEMPLATE.structures, ...town],
          recipes: DEFAULT_CONFIG.structures.recipes,
        }),
      }).missing
      const before = coverage(townStructuresFor('scripted'))
      const after = coverage([...townStructuresFor('scripted'), { kind: 'watchtower' }])
      expect(after.filter((m) => !before.includes(m))).toEqual(['watchtower facing sw'])
    })

    it('the four kinds the boot log named are this town\'s, and their footprints are its own', () => {
      const byKind = new Map(townStructuresFor('scripted').map((s) => [s.kind, s]))
      expect([...byKind.keys()].sort())
        .toEqual(['house', 'scaffolding', 'shed', 'standing_stone', 'storehouse', 'wagon'])
      // the footprints `structureArt.test.ts` cannot see from inside @sj/forge
      const cells = new Map(listCommittedBuildings().map((c) => [c.codexKind, c]))
      for (const kind of ['wagon', 'shed', 'scaffolding', 'standing_stone']) {
        const s = byKind.get(kind)!
        expect(cells.get(kind)!.manifest.footprint, kind).toEqual({ w: s.w, h: s.h })
      }
    })
  })

  it('gives each kind exactly one root, so two roots never fight over it', () => {
    // One root per class: `ingestProductionArt` reads `registerCommittedBuildings` and
    // `registerCommittedCast` and nothing else, so a kind cannot be claimed twice.
    for (const [label, kinds] of [
      ['buildings', listCommittedBuildings().map((c) => c.codexKind)],
      ['cast', listCommittedCast().map((c) => c.codexKind)],
      ['items', listCommittedItems().map((c) => c.kind)],
    ] as const) {
      expect(new Set(kinds).size, `two committed ${label} claim one codex kind`).toBe(kinds.length)
    }
  })
})

describe('ingestTerrainArt', () => {
  it('puts every flat tile kind and all 15 road-strip keys in the codex, idempotently', async () => {
    const db = openForgeDb(join(dir, 'terrain.db'))
    const codex = new AssetCodex(db)

    const first = await ingestTerrainArt(db)
    expect(first.every((e) => e.action === 'registered')).toBe(true)
    const ready = codex.listSince(0).filter((r) => r.status === 'ready' && r.class === 'terrain')
    const kinds = new Set(ready.map((r) => r.kind))
    for (const k of TERRAIN_TILE_KINDS) expect(kinds).toContain(k)
    for (const key of ROAD_AUTOTILE_KEYS) expect(kinds).toContain(roadAutotileKind(key))

    // a second boot over the same codex registers nothing — no duplicate rows to shadow
    const second = await ingestTerrainArt(db)
    expect(second.every((e) => e.action === 'unchanged')).toBe(true)
    expect(codex.listSince(0).filter((r) => r.class === 'terrain')).toHaveLength(ready.length)

    db.close()
  }, 30_000)
})

describe('ingestLibraryArt', () => {
  it('registers a sprite AND an icon for every one of the fifty, idempotently', async () => {
    const db = openForgeDb(join(dir, 'lib.db'))
    const codex = new AssetCodex(db)

    // The interior tileset rides in with them: it registers here because the terrain ingest
    // short-circuits on a resumed town and this one never does.
    const first = await ingestLibraryArt(db)
    const interiorKinds = INTERIOR_PIECES.map(interiorCodexKind)
    expect(first.map((e) => e.kind).sort())
      .toEqual([...LIBRARY.map((e) => e.kind), ...interiorKinds].sort())
    expect(first.every((e) => e.action === 'registered')).toBe(true)

    const items = codex.listSince(0).filter((r) => r.class === 'item')
    expect(items, 'fifty sprites and fifty icons').toHaveLength(LIBRARY.length * 2)
    const tileset = codex.listSince(0).filter((r) => r.kind?.startsWith('interior:') === true)
    expect(tileset, 'five wall elevations').toHaveLength(5)
    const bed = items.find((r) => r.kind === 'bed')!
    const manifest = parseLibraryItemManifest(bed.meta)
    expect(manifest).not.toBeNull()
    expect(manifest!.interior?.isBed).toBe(true)        // the meta the interior scene reads
    expect(bed.costUsd).toBe(0)                         // the generation booked its own spend

    const second = await ingestLibraryArt(db)
    expect(second.every((e) => e.action === 'unchanged')).toBe(true)
    expect(codex.listSince(0).filter((r) => r.class === 'item')).toHaveLength(LIBRARY.length * 2)
    db.close()
  }, 30_000)

  it('the catalog can furnish every interior kind the renderer places', () => {
    const known = new Set(LIBRARY.map((e) => e.kind))
    // A kind the plan no longer stands (the workshop shed) has no template room to check —
    // the renderer serves it INTERIOR_LAYOUTS instead, and that set is checked in @sj/web.
    const standing = INTERIOR_KINDS.filter((k) => cityStructures().some((c) => c.kind === k))
    expect(standing.length).toBeGreaterThan(0)
    for (const kind of standing) {
      const s = cityStructures().find((c) => c.kind === kind)
      expect(s, kind).toBeDefined()
      for (const f of s!.furnishings) {
        expect(known, `${kind} places ${f.kind}, which the library cannot paint`)
          .toContain(resolveFurnishingKind(f.kind))
      }
    }
  })
})

describe('ingestCastArt', () => {
  it('registers one packed sheet per founder, idempotently', async () => {
    const db = openForgeDb(join(dir, 'cast.db'))
    const codex = new AssetCodex(db)

    const first = await ingestCastArt(db)
    expect(first.map((e) => e.kind).sort())
      .toEqual([...FOUNDER_IDS].map((id) => `character:${id}`).sort())
    expect(first.every((e) => e.action === 'registered')).toBe(true)
    expect((await ingestCastArt(db)).every((e) => e.action === 'unchanged')).toBe(true)
    expect(codex.listSince(0).filter((r) => r.class === 'rig-part')).toHaveLength(FOUNDER_IDS.length)
    db.close()
  }, 30_000)
})

describe('the boot resolves every kind the world will ask for', () => {
  it('after a real boot ingest, nothing is left to the placeholder', async () => {
    const db = openForgeDb(join(dir, 'boot.db'))
    await ingestProductionArt(db)
    await ingestLibraryArt(db)
    const all = new AssetCodex(db).listSince(0).filter((r) => r.status === 'ready')
    const kindsOf = (klass: string) =>
      all.filter((r) => r.class === klass && r.kind !== null).map((r) => r.kind!)

    const items = itemArtCoverage(kindsOf('item'))
    expect(items.missing, coverageFailure('items', items).join('\n')).toEqual([])
    expect(items.orphans, coverageFailure('items', items).join('\n')).toEqual([])
    expect(items.covered).toHaveLength(LIBRARY.length * 2)

    const cast = castArtCoverage(kindsOf('rig-part'))
    expect(cast.missing, coverageFailure('cast', cast).join('\n')).toEqual([])
    expect(cast.orphans, coverageFailure('cast', cast).join('\n')).toEqual([])
    db.close()
  }, 30_000)

  it('and an empty codex reports every one of them, so the guard cannot go vacuous', () => {
    expect(itemArtCoverage([]).missing).toHaveLength(LIBRARY.length * 2)
    expect(castArtCoverage([]).missing).toHaveLength(FOUNDER_IDS.length)
  })
})
